"""Initial migration

Revision ID: 07772ad94e8f
Revises: 
Create Date: 2025-08-21 09:19:01.113249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07772ad94e8f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('commit_id', sa.String(length=36), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('extracted_entities', sa.JSON(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_commit_id'), 'analyses', ['commit_id'], unique=False)
    op.create_table('commits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commit_hash', sa.String(length=40), nullable=False),
    sa.Column('author_email', sa.String(length=255), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=False),
    sa.Column('project', sa.String(length=255), nullable=False),
    sa.Column('files_changed', sa.JSON(), nullable=False),
    sa.Column('issue_numbers', sa.JSON(), nullable=False),
    sa.Column('total_lines_changed', sa.Integer(), nullable=True),
    sa.Column('files_count', sa.Integer(), nullable=True),
    sa.Column('complexity_score', sa.Float(), nullable=True),
    sa.Column('impact_score', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('embedding_id', sa.String(length=255), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commits_author_email'), 'commits', ['author_email'], unique=False)
    op.create_index(op.f('ix_commits_branch'), 'commits', ['branch'], unique=False)
    op.create_index(op.f('ix_commits_commit_hash'), 'commits', ['commit_hash'], unique=True)
    op.create_index(op.f('ix_commits_project'), 'commits', ['project'], unique=False)
    op.create_index(op.f('ix_commits_timestamp'), 'commits', ['timestamp'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('document_type', sa.Enum('COMMIT', 'PULL_REQUEST', 'ISSUE', 'CODE_REVIEW', 'DOCUMENTATION', 'DISCUSSION', name='documenttypeenum'), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('indexed_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('project', sa.String(length=255), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('entities', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('has_embedding', sa.Integer(), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_author'), 'documents', ['author'], unique=False)
    op.create_index(op.f('ix_documents_document_type'), 'documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_documents_indexed_at'), 'documents', ['indexed_at'], unique=False)
    op.create_index(op.f('ix_documents_parent_id'), 'documents', ['parent_id'], unique=False)
    op.create_index(op.f('ix_documents_project'), 'documents', ['project'], unique=False)
    op.create_index(op.f('ix_documents_source_type'), 'documents', ['source_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_source_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_project'), table_name='documents')
    op.drop_index(op.f('ix_documents_parent_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_indexed_at'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_author'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_commits_timestamp'), table_name='commits')
    op.drop_index(op.f('ix_commits_project'), table_name='commits')
    op.drop_index(op.f('ix_commits_commit_hash'), table_name='commits')
    op.drop_index(op.f('ix_commits_branch'), table_name='commits')
    op.drop_index(op.f('ix_commits_author_email'), table_name='commits')
    op.drop_table('commits')
    op.drop_index(op.f('ix_analyses_commit_id'), table_name='analyses')
    op.drop_table('analyses')
    # ### end Alembic commands ###
