version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_PROVIDER=postgresql
      - DB_HOST=postgres
      - DB_NAME=git_analytics
      - DB_USER=postgres
      - DB_PASSWORD=postgres123
      - REDIS_URL=redis://redis:6379
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - postgres
      - redis
      - ollama
    volumes:
      - app_data:/app/data
      - app_logs:/app/logs

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: git_analytics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_KEEP_ALIVE=24h

  celery:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: celery -A src.infrastructure.queue.celery_queue worker --loglevel=info --concurrency=1 --pool=solo --queues=default,analysis
    environment:
      - DB_PROVIDER=postgresql
      - DB_HOST=postgres
      - DB_NAME=git_analytics
      - DB_USER=postgres
      - DB_PASSWORD=postgres123
      - REDIS_URL=redis://redis:6379
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - postgres
      - redis
      - ollama
    volumes:
      - app_data:/app/data

volumes:
  postgres_data:
  redis_data:
  ollama_data:
  app_data:
  app_logs: