app:
  name: "Git AI Analytics"
  version: "1.0.0"
  environment: "development"
  debug: true

server:
  host: "0.0.0.0"
  port: 8000
  workers: 1
  reload: true

database:
  provider: "sqlite"  # sqlite, postgresql
  sqlite:
    path: "data/git_analytics.db"
  postgresql:
    host: "localhost"
    port: 5432
    database: "git_analytics"
    username: "postgres"
    password: ""
  echo: false

cache:
  provider: "memory"  # memory, redis
  redis:
    url: "redis://localhost:6379"
    password: null
  memory:
    max_size: 1000
    default_ttl: 3600
  ttl:
    default: 3600
    search: 300
    chat: 600

ai:
  provider: "ollama"
  ollama:
    base_url: "http://localhost:11434"
    model: "llama3.2:3b"
    timeout: 30

messaging:
  provider: "celery"
  celery:
    broker_url: "redis://localhost:6379/0"
    result_backend: "redis://localhost:6379/0"

security:
  webhook_secret: null
  api_key: null

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"